### ISSUE TITLE
Experiment settings on LS-VID dataset

### ISSUE THREAD

**Issue by easquelcannotcode** [blue-blue272/BiCnet-TKS#3]
Thanks for your work! Could you please share your experiment settings on LS-VID dataset?

**Comment by blue-blue272** [comment]
> Thanks for your work! Could you please share your experiment settings on LS-VID dataset?

The setting is almost the same as MARS.
python train.py -d lsvid --root your path to LSVID --save_dir log-lsvid

**Comment by easquelcannotcode** [comment]
Thanks! I care about the gpu memory problem. I wonder if you use 8 frames for training, what is your total batch_size and how many gpus do you use? Besides, I would like to know the total memory of the gpus.

**Comment by blue-blue272** [comment]
> Thanks! I care about the gpu memory problem. I wonder if you use 8 frames for training, what is your total batch_size and how many gpus do you use? Besides, I would like to know the total memory of the gpus.

I use 2 2080Ti GPUs with 12G.
