### ISSUE TITLE
没有办法在duke上达到文章报告的效果。

### ISSUE THREAD

**Issue by ctrasd** [blue-blue272/BiCnet-TKS#4]
两张卡，batch-size=64的情况下跑模型只能得到93%的rank-1。请问一下跑duke的话需要做哪些参数上的调整吗？

**Comment by blue-blue272** [comment]
超参数是一样的，你是test.py测试的吗

**Comment by ctrasd** [comment]
唔，才发现train.py里的测试不一样。。test.py测试达到文章中效果了。感谢！
