### ISSUE TITLE
Why lsvid dataset use contrastive loss and other dataset use TripletLoss？

### ISSUE THREAD

**Issue by LOOKCC** [blue-blue272/BiCnet-TKS#5]
In your paper，there is nothing about contrastive loss，but I found that you use contrastive loss in lsvid dataset. So I want to ask the effect of this loss and does this loss is affected by dataset?

**Comment by blue-blue272** [comment]
The contrastive loss is more stable on lsvid dataset (we found that triplet loss is sensitive to random seeds on lsvid dataset). 

On the other datasets, the contrastive loss and triplet loss can achieve similar performance.
