### ISSUE TITLE
run the code ，map only 83？

### ISSUE THREAD

**Issue by DRACOyu** [blue-blue272/BiCnet-TKS#7]
hello，I run your code directly and keep the same parameters，but the map83 P1 88，Is there anything I should pay attention to？

**Comment by blue-blue272** [comment]
please run test.py for final evaluation.

**Comment by DRACOyu** [comment]
why？because the BN?

**Comment by blue-blue272** [comment]
because the train.py uses 4 frames to extract feature for each sequence. The test.py uses all frames of each sequence.

**Comment by DRACOyu** [comment]
Thanks. Back to read the code and the paper carefully
